{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-harmony
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/harmony_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/harmony/harmony_{{ version }}.tar.gz
  sha256: e0598c220ae90d1334e47c9958ccccf7defbe6ac530159bc69424923894f724a

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-irlba
    - r-rlang
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-irlba
    - r-rlang
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('harmony')"           # [not win]
    - "\"%R%\" -e \"library('harmony')\""  # [win]

about:
  home: software.broadinstitute.org/harmony
  license: GPL-3.0-only
  summary: Implementation of the Harmony algorithm for single cell integration, described in
    Korsunsky et al <doi:10.1038/s41592-019-0619-0>. Package includes a standalone Harmony
    function and interfaces to external frameworks.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
