{% set version = '1.3.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-loon.ggplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/loon.ggplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/loon.ggplot/loon.ggplot_{{ version }}.tar.gz
  sha256: 5bdfbf62b0d50d4c3502da714d0f3d954ba01e9c3b96c87d6902241b5d05e9a5

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggmulti
    - r-ggplot2
    - r-gridextra
    - r-loon >=1.3.2
    - r-patchwork
    - r-rlang
    - r-scales
  run:
    - r-base
    - r-ggmulti
    - r-ggplot2
    - r-gridextra
    - r-loon >=1.3.2
    - r-patchwork
    - r-rlang
    - r-scales

test:
  commands:
    - $R -e "library('loon.ggplot')"           # [not win]
    - "\"%R%\" -e \"library('loon.ggplot')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=loon.ggplot
  license: GPL-2.0-only
  summary: Provides a bridge between the 'loon' and  'ggplot2' packages.  Extends the grammar
    of ggplot to add clauses to create interactive 'loon' plots. Existing ggplot(s)
    can be turned into interactive 'loon' plots and 'loon' plots into static ggplot(s);
    the function 'loon.ggplot()' is the bridge from one plot structure to the other.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
