{% set name = "perl-config-any" %}
{% set version = "0.32" %}
{% set sha256 = "68da2a5cf25faedd4d24cf3d0d570995c199d5b950108a2de78d40deced36150" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/H/HA/HAARG/Config-Any-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl
    - perl-app-cpanminus
    - perl-extutils-makemaker
  run:
    - perl
    - perl-app-cpanminus

test:
  imports:
    - Config::Any
    - Config::Any::Base
    - Config::Any::General
    - Config::Any::INI
    - Config::Any::JSON
    - Config::Any::Perl
    - Config::Any::XML
    - Config::Any::YAML

about:
  home: https://metacpan.org/dist/Config-Any
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: 'Load configuration from different file formats, transparently'
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1

extra:
  recipe-maintainers:
    - cbrueffer
