{% set version = '0.1.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcppziggurat
  version: {{ version|replace("-", "_") }}

source:
  fn: RcppZiggurat_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/RcppZiggurat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppZiggurat/RcppZiggurat_{{ version }}.tar.gz
  sha256: db6d5fd3a77ac9473bf21f84b65da3c6e485f9ed33f5313bbf0ec852b71db97e

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-rcppgsl
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-rcppgsl

test:
  commands:
    - $R -e "library('RcppZiggurat')"           # [not win]
    - "\"%R%\" -e \"library('RcppZiggurat')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RcppZiggurat
  license: GPL (>= 2)
  summary: The Ziggurat generator for normally distributed random numbers, originally proposed
    by Marsaglia and Tsang (2000,  <doi:10.18637/jss.v005.i08>) has been improved upon
    a few times starting with Leong et al (2005, <doi:10.18637/jss.v012.i07>). This
    package provides an aggregation in order to compare different implementations in
    order to provide an 'faster but good enough' alternative for use with R and C++
    code.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
