{% set name = "perl-autoloader" %}
{% set version = "5.74" %}
{% set sha256 = "2fac75b05309f71a6871804cd25e1a3ba0a28f43f294fb54528077558da3aff4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SM/SMUELLER/AutoLoader-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - AutoLoader
    #- AutoSplit

about:
  home: https://metacpan.org/dist/AutoLoader
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: 'load subroutines only on demand'
  license_file:
    - Copying
    - Artistic

extra:
  recipe-maintainers:
    - cbrueffer
