{% set version = '0.6-6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmpi
  version: {{ version|replace("-", "_") }}

source:
  fn: Rmpi_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/Rmpi_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/Rmpi/Rmpi_{{ version }}.tar.gz
  sha256: d8fc09ad38264697caa86079885a7a1098921a3116d5a77a62022b9508f8a63a

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('Rmpi')"  # [not win]
    - "\"%R%\" -e \"library('Rmpi')\""  # [win]

about:
  home: http://www.stats.uwo.ca/faculty/yu/Rmpi
  license: GPL (>= 2)
  summary: An interface (wrapper) to MPI APIs. It also  provides interactive R manager and worker
    environment.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
