{% set version = '0.1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bayesmodels
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bayesmodels_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bayesmodels/bayesmodels_{{ version }}.tar.gz
  sha256: f9e3adc5782d44f3ab27b2d38a872ea032b125c4ac7dd1aeffeee6f81d1224d5

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bass
    - r-rlgt
    - r-bayesforecast
    - r-brms
    - r-bsts
    - r-cli
    - r-crayon
    - r-dials
    - r-dplyr
    - r-magrittr
    - r-modeltime
    - r-parsnip
    - r-purrr
    - r-rlang >=0.1.2
    - r-rstan
    - r-rstudioapi
    - r-tibble
    - r-timetk
    - r-workflows
  run:
    - r-base
    - r-bass
    - r-rlgt
    - r-bayesforecast
    - r-brms
    - r-bsts
    - r-cli
    - r-crayon
    - r-dials
    - r-dplyr
    - r-magrittr
    - r-modeltime
    - r-parsnip
    - r-purrr
    - r-rlang >=0.1.2
    - r-rstan
    - r-rstudioapi
    - r-tibble
    - r-timetk
    - r-workflows

test:
  commands:
    - $R -e "library('bayesmodels')"           # [not win]
    - "\"%R%\" -e \"library('bayesmodels')\""  # [win]

about:
  home: https://github.com/AlbertoAlmuinha/bayesmodels
  license: MIT
  summary: 'Bayesian framework for use with the ''tidymodels'' ecosystem. Includes the following
    models: Sarima, Garch, Random walk (naive), Additive Linear State Space Models,
    Stochastic Volatility Models from ''bayesforecast'' package, Adaptive Splines Surfaces
    from ''BASS'' package and ETS from ''Rlgt'' package.'
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
