{% set version = '0.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidymodels
  version: {{ version|replace("-", "_") }}

source:
  fn: tidymodels_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tidymodels_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidymodels/tidymodels_{{ version }}.tar.gz
  sha256: 0c845813bc3c0e38131e1b06c57137d52a327045739d6adfff3a62db264c54c6

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-broom >=0.5.0
    - r-cli >=1.0.0
    - r-crayon >=1.3.4
    - r-dplyr >=0.7.6
    - r-ggplot2 >=3.0.0
    - r-infer >=0.3.0
    - r-magrittr >=1.5
    - r-pillar >=1.3.0
    - r-purrr >=0.2.5
    - r-recipes >=0.1.3
    - r-rlang >=0.2.1
    - r-rsample >=0.0.2
    - r-rstudioapi >=0.7
    - r-tibble >=1.4.2
    - r-tidyposterior >=0.0.1
    - r-tidypredict >=0.2.0
    - r-tidytext >=0.1.9
    - r-yardstick >=0.0.1
  run:
    - r-base
    - r-broom >=0.5.0
    - r-cli >=1.0.0
    - r-crayon >=1.3.4
    - r-dplyr >=0.7.6
    - r-ggplot2 >=3.0.0
    - r-infer >=0.3.0
    - r-magrittr >=1.5
    - r-pillar >=1.3.0
    - r-purrr >=0.2.5
    - r-recipes >=0.1.3
    - r-rlang >=0.2.1
    - r-rsample >=0.0.2
    - r-rstudioapi >=0.7
    - r-tibble >=1.4.2
    - r-tidyposterior >=0.0.1
    - r-tidypredict >=0.2.0
    - r-tidytext >=0.1.9
    - r-yardstick >=0.0.1

test:
  commands:
    - $R -e "library('tidymodels')"           # [not win]
    - "\"%R%\" -e \"library('tidymodels')\""  # [win]

about:
  home: https://github.com/tidymodels/tidymodels
  license: GPL-3
  summary: The tidy modeling "verse" is a collection of package for  modeling and statistical
    analysis that share the underlying design philosophy, grammar, and data structures
    of the tidyverse.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
